<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.tkit.onecx</groupId>
    <artifactId>onecx-quarkus3-parent</artifactId>
    <version>{{parentVersion}}</version>
  </parent>

  <groupId>{{group}}</groupId>
  <artifactId>{{name}}</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>{{name}}</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>
    <quarkus.package.type>fast-jar</quarkus.package.type>
  </properties>

  <dependencies>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-rest</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-rest-jackson</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-hibernate-orm</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-jdbc-postgresql</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-liquibase</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-smallrye-health</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-micrometer-registry-prometheus</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-smallrye-openapi</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-hibernate-validator</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-opentelemetry</artifactId></dependency>
    <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-oidc</artifactId></dependency>
    <dependency><groupId>org.tkit.quarkus</groupId><artifactId>tkit-quarkus-jpa</artifactId></dependency>
    <dependency><groupId>org.tkit.quarkus</groupId><artifactId>tkit-quarkus-log-cdi</artifactId></dependency>
    <dependency><groupId>org.tkit.quarkus</groupId><artifactId>tkit-quarkus-log-json</artifactId></dependency>
    <dependency><groupId>org.tkit.quarkus</groupId><artifactId>tkit-quarkus-rest</artifactId></dependency>
    <dependency><groupId>org.tkit.quarkus</groupId><artifactId>tkit-quarkus-jpa-tenant</artifactId></dependency>
    <dependency><groupId>org.tkit.quarkus</groupId><artifactId>tkit-quarkus-rest-context</artifactId></dependency>
    <dependency><groupId>org.tkit.onecx.quarkus</groupId><artifactId>onecx-tenant</artifactId></dependency>
    <dependency><groupId>org.tkit.onecx.quarkus</groupId><artifactId>onecx-core</artifactId></dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>generate-rest</id>
            <goals><goal>generate</goal></goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/openapi/{{name}}-v1.yaml</inputSpec>
              <generatorName>jaxrs-spec</generatorName>
              <library>quarkus</library>
              <interfaceOnly>true</interfaceOnly>
              <useMicroProfileOpenAPIAnnotations>true</useMicroProfileOpenAPIAnnotations>
              <useJakartaEe>true</useJakartaEe>
              <addCompileSourceRoot>true</addCompileSourceRoot>
              <configOptions>
                <openApiNullable>false</openApiNullable>
                <dateLibrary>java8</dateLibrary>
                <useBeanValidation>true</useBeanValidation>
                <serializableModel>true</serializableModel>
                <returnResponse>true</returnResponse>
              </configOptions>
              <apiPackage>{{package}}.rs</apiPackage>
              <modelPackage>{{package}}.dto</modelPackage>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
